### ISSUE TITLE
Following Apple's standards

### ISSUE THREAD

**Issue by ameykshirsagar** [PasiSalenius/LightMQTT#17]
Hi,
I am trying to implement your library in iOS for my Cordova MQTT plugin.
I just want to know whether it is following Apple's Standards mentioned [here](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/CommonPitfalls/CommonPitfalls.html)
I am getting a connection in localhost but the remote connection [test.mosquitto.org](test.mosquitto.org) is getting closed on both secure and insecure ports

Thank you

**Comment by PasiSalenius** [comment]
Hello,

I've tried to make it behave as well as possible, while also keeping the code simple and compact. In my testing the sockets stay open also after the LightMQTT client is disconnected. They are waiting in the blocking read() method of the InputStream.

But reliably, after 60 seconds, the read() method errors out with a -1 value, and the background thread exits cleanly as the InputStream is closed at this point. The LightMQTT instance is then deinitialized.

I should look into setting SO_KEEPALIVE for the sockets, to possibly make this 60 seconds timeout smaller.

Pasi

**Comment by PasiSalenius** [comment]
I actually just tried setting SO_KEEPALIVE to true InputStream with setsockopt. It does not seem to help with releasing the socket read any sooner, though.

**Comment by ameykshirsagar** [comment]
In localhost, the connection remains stable.

**Comment by PasiSalenius** [comment]
If there is nothing specific that you would like to be added to LightMQTT, I will close this issue. I can't say what the problems you're seeing with Cordova might be related to, but in my use there have been no problems connecting to remote hosts from an iOS device.

**Comment by ameykshirsagar** [comment]
I resolved the issue on my side. I have made some changes about keep alive. And some background thread issues regarding Cordova.
If you don't mind give a look at my pull request. And I will close the issue myself

**Comment by ameykshirsagar** [comment]
Thank you so much for your help @PasiSalenius
