### ISSUE TITLE
No option for TLS

### ISSUE THREAD

**Issue by travisgriggs** [PasiSalenius/LightMQTT#2]
Currently, there is no option for TLS support. I'd like to propose connect() get an optional argument, something like:

func connect(useTLS:Bool = false) -> Bool

I'll work up another PR for that...

**Comment by PasiSalenius** [comment]
This sounds like the right approach, please keep the PRs coming.

I should have time to check everything this weekend, and accept them in. I'll also add my latest fixes to the library.

**Comment by PasiSalenius** [comment]
I think this can be closed.
