### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by travisgriggs** [PasiSalenius/LightMQTT#24]
I've noticed of late that I'm seeing this deprecation warning. I'll try to submit a PR soon.

`/Users/travisg/Projects/twigpilot_remote_ios/twigpilot_remote_ios/LightMQTT.swift:213:27: 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead`

**Comment by PasiSalenius** [comment]
That would be great, thanks.

Just today I was watching the WWDC session where it was recommended to move from BSD sockets to the new Network framework, introduced in iOS 12. I'll see if I get anywhere with that.

**Comment by travisgriggs** [comment]
6 months late on my part... :) But submitted now.
