### ISSUE TITLE
withUnsafeBytes() deprecated w/ Swift 5

### ISSUE THREAD

**Issue by ThyGat** [PasiSalenius/LightMQTT#26]
Thank you again for this great MQTT client: light and safe.
However, there is a deprecation warning for:
withUnsafeBytes(body: (UnsafePointer<ContentType>) throws -> ResultType)

sorry, tried to fix it but with no luck.

**Comment by PasiSalenius** [comment]
Fixed by https://github.com/PasiSalenius/LightMQTT/commit/68645173a70769bbf7a18c2a2bbe686f55363e15
